### ISSUE TITLE
How to configure the theme, make it look like the demo?

### ISSUE THREAD

**Issue by Alwayswithme** [asurbernardo/amperage#23]
Hi, Asur

I clone amperage, using the `master` branch,
```
git clone https://github.com/asurbernardo/amperage.git
cd amperage/exampleSite/ && hugo server --themesDir ../../
```

but it looks different from what I expect like the [demo page](https://themes.gohugo.io/theme/amperage/).

and the `v1` branch having problem to display post's date and tag

I like your theme, thank you for your work.

**Comment by asurcodes** [comment]
Hello @Alwayswithme, thank you so much for the report!

This is due to recent change on the listing styles I have been working on, I have uploaded a fix already! :smile: 

I know the setup right now is not ideal but I'm working on a release cycle to avoid these errors in the future. :+1:

If you have any other feedback or feature request please tell me about it!

**Comment by Alwayswithme** [comment]
Thank you so much for your speedy reply,  @asurbernardo 

I see, the version that the demo using is 1acb3b5db778f28e5f3476d82ddbf95f7e34d8ac

The latest version you working on is great. 👏

But I prefer the demo because it look much cleaner without those `keep reading` button. 
And the post's title looks concise，how about make it neater with or without the image front matter? 

Hope you make a stable release ASAP 😬

**Comment by asurcodes** [comment]
@Alwayswithme Yes, I'm planning to create a stable release and move the active branch to `development`.

You are completely right, later today I'm going to make the summary image not mandatory, and you will still be able to set the `og:image` and `twitter:image` using their specific configuration options.

I'm also going to clean the listings, but I like the way the buttons look. Remember you can tweak any style you want using the `assets/custom.scss` file. :smile:

**Comment by asurcodes** [comment]
@Alwayswithme I've settled the look and feel of the theme for now, you can check it out @ https://asur.dev/en/

I've created a v1.0 release and as I said I'm going to move the activity to the `development` branch and keep `master` stable. 

Thank you so much for your feedback! I'm closing the issue, feel free to open more in the future! :+1: 

PS: I made the summary image not mandatory as well, now you can just remove it from the frontmatter.
