### ISSUE TITLE
Port to Gatsby 

### ISSUE THREAD

**Issue by BadBrahmin** [asurbernardo/amperage#26]
Hey Asur, 

Would you be porting this to Gatsby by any chance? Would love to have it there.

Cheers!

**Comment by asurcodes** [comment]
Hello @BadBrahmin, I'm not currently planning to port the theme to any other framework / static generator. 

This is more of a personal project I use on my website so a port wouldn't make sense for me, but please, feel free to use the code however you see fit! 😄
