### ISSUE TITLE
Picture can't be displayed

### ISSUE THREAD

**Issue by ghost** [asurbernardo/amperage#27]
https://asur.dev/

Picture can't be displayed

**Comment by asurcodes** [comment]
@LGTMXD Cannot replicate. More details are welcome.

**Comment by ghost** [comment]
I found that pics cached on https://cdn.amp.xxxx are blocked on China.

**Comment by asurcodes** [comment]
@LGTMXD It seems like China blocks Google URLs, this has nothing to do with the theme, I'm sorry but I cannot help you with this.
