### ISSUE TITLE
"assets/custom.scss" is not transpiled

### ISSUE THREAD

**Issue by muratagawa** [asurbernardo/amperage#30]
Hi, Asur.
Thank you for sharing nice theme.

I found a bug while customizing stylesheets.

As written in README.md, I created `themes/amperage_custom/assets/custom.scss` and ran `hugo server`. But styles in `custom.scss` were never reflected.
(`amperage_custom/` is just copy of normal `amperage/`)

I'm using "hugo_extended_0.72.0_Windows-64bit".

Any suggestions on what I can do to get it to work?

**Comment by asurcodes** [comment]
Hello @muratagawa, thank you for the kind words and for the report.

You don't need to change the theme at all, just create an assets folder in the root of your website, and inside create the `custom.scss` file.

Anyway, I will try to replicate the error and check if any of the Hugo Resources API has changed. If you are aware of any let me know.

For the record, the place where this takes place is: https://github.com/asurbernardo/amperage/blob/master/layouts/partials/head/styles.html

**Comment by muratagawa** [comment]
I found I have been editing the wrong file. 

- wrong: `<hugo_project>/themes/amperage/assets/custom.scss` (created by myself)
- correct: `<hugo_project>/assets/custom.scss`

Now I can override styles! Thanks for your advice.
