### ISSUE TITLE
Responsive menu

### ISSUE THREAD

**Issue by roshanjonah** [asurbernardo/amperage#32]
Great theme :) I was wondering if you had time to add responsive menu because the current one doesn't seem to scale down or go into mobile menu mode.

Any one of these perhaps? 
https://theampbook.com/ch4/
https://amp.dev/documentation/components/amp-nested-menu/?format=websites
https://amp.dev/documentation/components/amp-mega-menu/?format=websites

**Comment by asurcodes** [comment]
Thank you @roshanjonah. 

The menu to have a overflow scroll on the X axis is a conscious decision for the sake of simplicity but you always can customize it to your needs overriding the `/layouts/partials/header/menu.html` file and adding your own styles.

If you come up with a simple and elegant solution please, create a PR and I will consider it! :smiley:
