### ISSUE TITLE
Breadcrumb navigation

### ISSUE THREAD

**Issue by roshanjonah** [asurbernardo/amperage#33]
How do I make the breadcrumb navigation displayed on the top? Sorry this might feel like a very newbie question but I couldn't find information about this anywhere.

**Comment by roshanjonah** [comment]
I got here but it's displaying the URL twice and therefore invalid URLs - added it to here `themes/amperage/layouts/_default/single.html` for trying it out. 

```
 <section>
 <div class="bread-container shadow">
 {{ $url := replace .Permalink ( printf "%s" .Site.BaseURL) "" }}
 {{ $.Scratch.Add "path" .Site.BaseURL }}
 <ol class="breadcrumbs">
 <li>Navigation: </li>
   <li><a href="/">home</a></li>
   {{ range $index, $element := split $url "/" }}
     {{ $.Scratch.Add "path" $element }}
       {{ if ne $element "" }}
       <li>&rarr; <a href='{{ $.Scratch.Get "path" }}'>{{ . }}</a></li>
       {{ $.Scratch.Add "path" "/" }}
       {{ end }}
   {{ end }}
 </ol>
 </div>
 </section>
```

Any help would be greatly appreciated :)

**Comment by asurcodes** [comment]
This is not supported by the theme. If you want to add it to your own page, I recommend you to extend https://github.com/asurbernardo/amperage/blob/master/layouts/partials/header/base.html on your own project.

Breadcrumbs are already implemented for structured data, so you can base your code on it if you want, you can find it in https://github.com/asurbernardo/amperage/blob/master/layouts/partials/structured-data/breadcrumbs.html.

If you feel like your change can improve the theme, your PR is welcome! 😄
