### ISSUE TITLE
Not able to overwrite css.

### ISSUE THREAD

**Issue by ketanip** [asurbernardo/amperage#38]
Hello, I'm new to this Hugo game and static sites altogether and **I tried all** I can do but I am not able to change css. I followed instructions by you but I am unable to change it 😔. **I just wanted to change font-family** to **verdena or roboto**, What should I do, please help .

**Comment by roshanjonah** [comment]
- Go to `themes/amperage/assets/theme.scss`
- Edit line 7 with your desired font something like
`font-family: Verdana,sans-serif;`

- If you want Roboto, you need to copy Google Fonts code for roboto into `themes/amperage/layouts/partials/head/base.html` and then you can use that font in the above code. 

Hope that helps :)

**Comment by ketanip** [comment]
It is still not changing.

**Comment by asurcodes** [comment]
Hello @KetanIP, you can extend the Amperage theme **on your own project** and override the styles by creating a `assets/custom.scss` file. **You don't need to modify any theme files** as stated on the [README](https://github.com/asurbernardo/amperage#-customize-styles).

For you just go to Google Fonts and generate the font weights and styles of your linking, like [this one](https://fonts.googleapis.com/css2?family=Roboto&display=swap) and paste the content on your `custom.scss` file.

Then just apply on that very same file the font on the selectors you want it on:

```
body {
    font-family: 'Roboto', sans-serif;
}
```

**REMEMBER**: This may have performance considerations. I would consider using Verdana, it's included in all major browsers/OSs, so you can avoid extra downloads and you can also skip the Google Fonts step and use it directly in your selector.
