### ISSUE TITLE
Start page

### ISSUE THREAD

**Issue by sjs-sudo** [asurbernardo/amperage#45]
Dear Asur,

is it possible to remove the post preview as default start page and use for example an image instead?

Thank you,
Jasmin

**Comment by asurcodes** [comment]
Hello!

This is currently not supported by the theme, but you can always fork it and modify it or extend it if you want to.

I would recommend you to take a look at the GoHugo docs for layout lookup order if you choose to extend the theme: https://gohugo.io/templates/lookup-order/
