### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by ycycxz** [asurbernardo/amperage#46]
> https://amp.dev/documentation/examples/style-layout/dark_mode_toggle/

**Comment by asurcodes** [comment]
Hello @Scaleya, this toggle you link only toggles the browser preference to be able to apply media queries on dark mode, the dark theme implementation is still needed.

IMO that would defeat the purpose of CSS minimalism of the theme, remember you can always fork the repository and implement it by yourself or extending the theme CSS following the README.
